Repository SharonIV0x86/Appledore, pull requests merged in 2025-01, with the labels that each got.

#3 Add getNeighbors function to GraphMatrix and Implement Social Network Example
  examples/socialNetwork.cpp
  include/GraphMatrix.h
Labels: enhancement, INTERMEDIATE, SWOC

#9 [Feat] Degree calculation GraphMatrix.h. #5
  examples/directedGraph.cpp
  examples/socialNetwork.cpp
  examples/undirectedGraph.cpp
  include/GraphMatrix.h
Labels: enhancement, INTERMEDIATE, SWOC

#14 Added all paths
  examples/allPaths.cpp
  include/GraphMatrix.h
Labels: enhancement, INTERMEDIATE, SWOC

#22 Feat : Add vertex removal functionality to MixedGraph
  examples/vertexRemoval.cpp
  include/GraphMatrix.h
  include/MixedGraph.h
Labels: enhancement, good first issue, BEGINNER

#16 Added degree calculation functions and example
  examples/degreeCal.cpp
  include/MixedGraph.h
Labels: enhancement, INTERMEDIATE, SWOC

#30 Add Code of Conduct
  Code of Conduct.md
Labels: enhancement, BEGINNER, SWOC

#31 Added isolated vertices feature and example usage
  examples/isolatedVertices.cpp
  include/GraphMatrix.h
Labels: BEGINNER, SWOC, feature addition

#33 [Fix] Fixed removeVertex in GraphMatrix.
  include/GraphMatrix.h
Labels: bug, BEGINNER, SWOC

#23 Feat : Add custom exception classes for graph operations
  include/GraphExceptions.h
Labels: enhancement, ADVANCED, SWOC

#26 Add graph density calculation method
  include/GraphMatrix.h
Labels: enhancement, good first issue, BEGINNER, SWOC

#41 [Enhancement] Refactor GraphMatrix and MixedGraphMatrix Classes to Use a Common Base Class
  include/GraphMatrix.h
  include/MatrixRep.h
  include/MixedGraph.h
Labels: enhancement, Self Development

#44 [Fix] fixed missing include and inheritance
  include/MixedGraph.h
Labels: bug, Self Development

#29 Addressing #20, added pathLimit Functiionality
  examples/allPaths.cpp
  include/GraphMatrix.h
Labels: enhancement, ADVANCED, SWOC

#43 Add Custom Edge Sorting with Predicate Function added edgeRetrieval.cpp
  examples/edgeRetrieval.cpp
  include/GraphMatrix.h
Labels: enhancement, ADVANCED, SWOC

#46 Fixed removeVertex() function
  examples/vertexRemoveUpdated.cpp
  include/MixedGraph.hpp
Labels: bug, BEGINNER, SWOC, Under Testing
